# Generated by Django 4.2.5 on 2023-09-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('condition', models.CharField(max_length=255)),
                ('date_added', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckOutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('condition_at_checkout', models.CharField(max_length=255)),
                ('condition_at_return', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_logs', to='assets.assets')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_logs', to='employees.employee')),
            ],
        ),
    ]
